### ISSUE TITLE
Epic: Simplify the structure of the core repo and factor out Epoch in its own repo

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1276]
This epic specifies the new envisioned and simplified project structure as well as concrete incremental steps we can take towards this goal.

### Overview

Our current is very bloated and it is hard for newcomers to find their way through the forest of packages and directories. This structure has been been mostly dictated by Xtext and Eclipse. However, since we are moving away from Eclipse as our primary development IDE and Epoch is only one of our supported LF IDEs, we should aim at freeing our core repository from the constraints and overhead that Eclipse imposes. The best way to do this, is to separate our "core" repository from Epoch. Ideally, we strip the lingua-franca repository from all unnecessary Eclipse dependencies and Eclipse related code. This should instead be hosted in a separte Epoch repository where lingua-franca is a submodule.

### The Goal

- The lingua-franca repository should look something like this: 
  ```Text
  lingua-franca/
  ├── bin/
  ├── lib/
  ├── src/
  ├── test/
  ```
  Of course we will need some additional files and directories for gradle and other meta files, but the idea is to have a single point of entry for the source code. All code that is needed for our command line tools and the language server, should be located within `src/`. This includes the contents of `org.lflang`, `org.lflang.lfc`, `org.lflang.diagrams` and `org.lflang.lds`. The primary build tool for this repository would be gradle and any IDE could be used for development
- The Epoch repository would look similar to the current lingua franca repository. Most notably, `org.lflang` would become a submodule and point to the lingua-franca repository. The primary build tool for this repository would be maven and Eclipse the main IDE for development.
- Since the restructuring will be a breaking change, we also want to use the opportunity to fix #1078 and #423. The goal is to clean our git history and push the cleaned history to a new main branch. This way we can keep the old master branch for legacy, but start developing on main in our freshly cleaned up repo.

### Action Items
- [x] Bundle the core functionality of LF in `org.lflang`
  - [x] #1421
  - [x] Move contents of `org.lflang.diagram` to a subpackage `diagram` within `org.lflang`
  - [x] Build  language server with Gradle which depends on publication of KlighD package
  - [x] Remove `org.lflang.lds`because no longer needed
  - [x] Remove "Eclipse switch" from `mwe2` file in `lingua-franca` repo
  - [x] #1800
- [x] https://github.com/lf-lang/lingua-franca/issues/1491 
- [ ] Move actions for building the RTI and other files referring to the RTI to reactor-c or to a standalone RTI repository (also see https://github.com/lf-lang/reactor-c/issues/5)
~- [ ] Find Epoch specific code in the code-base and move it out of `org.lflang`.~
  - ~This includes the `EclipseErrorReporter`, but also any code where we check the mode of operation (standlone vs epoch)~
- [x] Move all Epoch specific code to its own repository, which its own `mwe2` file that toggles the "Eclipse switch"
- [x] Apply the new structure to the lingua-franca repository and update the Gradle config accordingly. This includes:
  - [x] #1801
  - [x] https://github.com/lf-lang/lingua-franca/issues/1514
- [x] #1078 
- [ ] #423 
- [x] Make lingua-franca a submodule of Epoch

#### Optional:
- [ ] #937 
      The planned restructuring poses an opportunity for publishing the core package of LF on Maven central.

**Comment by cmnrd** [comment]
Thanks for the remark. I made this now an explicit part of the action items.

**Comment by cmnrd** [comment]
Closing this as the major part of the work is complete and the remaining loibts are Kind of open ended

**Comment by lhstrh** [comment]
Should we still rename `master` to `main`? It will break a lot of things...

**Comment by cmnrd** [comment]
I think we should. Mostly because half of our repos use `main` and it would be nice to get some consistency...

The issue currently has the 0.6.0 milestone assigned, but I wouldn't mind pushing it a bit further down the road.

**Comment by lhstrh** [comment]
OK, makes sense. I'd rather just bite the bullet honestly...so I'm OK with doing it as part of 0.6.0...
