### ISSUE TITLE
Epic: Implement a local federated (affiliated) execution strategy in the C++ target

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1382]
The same underlying principles used for coordinating federated execution over network connections can also be used to coordinate the execution of reactors in the same process. This allows each affiliated reactor to maintain its own logical time line. This should allow us to relax the barrier synchronization imposed by our runtimes. At the same time, the affiliated execution is expected to be much more efficient than the federated execution as all network communication can be replaced with function calls.

Work items:
 - [ ] Merge #1221 
 - [ ] Build the infrastructure to generate multiple unconnected affiliates.
 - [ ] Implement a "simple" coordination strategy based on the current centralized federated coordination. This strategy should only support `NET` and `TAG` messages and not consider the `PTAG` messages (partial time advance grant). This solution will not support zero delay cycles in the reactor graph.
 - [ ] Implement a more advanced coordination strategy that supports `PTAG` and hence also supports cyclic reactor graphs.
 - [ ] Decide on a name. Currently we call the overall program an "affiliation" and the individual parts "affiliate"

Future work (not part of this Epic, but important items to work on later):
 - Find a mechanism to automatically decide which reactors should become affiliates.
