### ISSUE TITLE
Epic: LF syntax enhancements

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#1492]
This is an attempt to give an overview of planned changes to the LF syntax, and also of those changes that are still in the discussion/design state. (I'll fork off some new tickets to have more room for discussing individual items)

The goals of most of these changes are
- Make the syntax more expressive (new expression forms, constructor enhancements, required parameters)
- Make the syntax more consistent, both internally, and w.r.t. our target languages.
- Better specify some parts of code generation (eg parameter scope, preamble scope). This makes it easier to understand LF code, to implement code generators, and to build comprehensive test suites.

## In progress/planned

- [ ] #986
    - [ ] #1441: cleanup initializer grammar
    - [ ] Introduce `=` initializer syntax, deprecate other syntaxes in targets other than C++
    - [ ] Introduce new expression forms, including
        - [ ] Constructor call shorthand for Rust/TS/Python
        - [ ] List expressions
- [ ] #623 
- [ ] #657 
- [ ] @cmnrd C++ code generation change: use a struct to pass parameters with designated initializers. Initializer lists don't work properly as reactor parameters currently.

## Design work needed

Currently unplanned or not discussed at all

TODO @oowekyala: for those items that have no ticket, I'll open one soon to add details and call for discussion.

- [ ] #1238
- [ ] #1479
    - [ ] Proposals: `token<t>`, or just `@token` on the port?
- [ ] Preamble semantics
- [ ] Parameter semantics
- [ ] LF Instance declaration syntax
