### ISSUE TITLE
Implement Savina benchmarks in C

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#632]
This issue is to keep track of the current status of the C benchmarks.

*  micro benchmarks
    - [x] Big -> Arthur
    - [x] Chameneos -> Marten
    - [x] Count
    - [x] Fork Join
    - [x] Ping Pong
    - [x] Thread Ring
* concurrency benchmarks
    - [ ] Banking
        - [X] Implement
        - [ ] Resolve #433
        - [ ] Merge #624 
    - [x] Barber -> Matt
        - [x] Implement
        - [x] Integrate with runner script
        - [x] Address the comments made in #401 
        - [x] Merge #671
    - [x] Bounded Buffer (ProdCons) -> Matt
        - [x] Update to align with C++ version
    - [x] Cigarette Smokers
        - [x] Implement
        - [x] Integrate with runner script
        - [x] Address the comments made in #445
    - [x] Concurrent Dictionary -> Matt
        - [x] First implementation
        - [x] Check if it aligns with the C++ version
        - [x] Integrate with the runner script
    - [x] Concurrent Sorted List -> Matt
        - [x] First implementation
        - [x] Check if it aligns with the C++ version
        - [x] Integrate with the runner script
    - [x] Logistic Map
    - [x] Philosophers -> Christian
        - [x] Align C and C++ version
        - [x] cog the main reactor and integrate with runner script
* parallelism benchmarks
    - [x] APSP -> Soroush
    - [x] ASTAR -> Soroush
    - [x] Filter Bank
    - [x] N Queens K Solutions -> Arthur
        - [x] Implement
        - [x] Fix warnings regarding duplicated frees (see #721)
    - [x] Pi Precise -> Christian
        - [x] Simplify and align with C++ version
        - [x] Fix FIXMEs
    - [x] Radix Sort
        - [x] use cog and multiports/banks to instantiate all workers 
        - [x] Investigate performance issues (in C++)
        - [x] Make sure updated C++ version and C version align
    - [x] Rec Matrix Multiplication -> Peter
    - [x] Trapezoid
* other tasks:
    - [ ] consistent use of deque
    - [x] C version of MatMul is slower due to caching effects -> use BenchmarkRunner reactor!?
    - [x] What to do with Smokers.lf? (Thee's version of the smoker problem)

**Comment by cmnrd** [comment]
Closing this since most of the tasks are done. There are separate issues for the remaining tasks (#765, #624).
